from odoo import fields, models

class ViabilidadeDados(models.Model):
    _name = "viabilidade.dados"

    identificacao = fields.Char(string="Identificação")
    celula = fields.Char(string="Celula")
    estacao_abastecedora = fields.Char(string="Estação abastecedora")
    uf = fields.Char(string="UF")
    municipio = fields.Char(string="Municipio")
    localidade = fields.Char(string="Localidade")
    cod_localidade = fields.Char(string="Cod Localidade")
    localidade_abrev = fields.Char(string="Localidade abreviada")
    logradouro = fields.Char(string="Logradouro")
    cod_logradouro = fields.Char(string="Cod Logradouro")
    num_fachada = fields.Char(string="Num Fachada")
    complemento = fields.Char(string="Complemeto")
    complemento2 = fields.Char(string="Complemento 2")
    complemento3 = fields.Char(string="Complemento 3")
    cep = fields.Char(string="CEP")
    bairro = fields.Char(string="Bairro")
    cod_survey = fields.Char(string="Cod Survey")
    quantidade_ums = fields.Char(string="Quantidade UMS")
    cod_viabilidade = fields.Char(string="Cod Viabilidade")
    tipo_viabilidade = fields.Char(string="Tipo Viabilidade")
    tipo_rede = fields.Char(string="Tipo de Rede")
    ucs_residenciais = fields.Char(string="UCS Residenciais")
    ucs_comerciais = fields.Char(string="UCS Comerciais")
    nome_cdo = fields.Char(string="Nome CDO")
    id_endereco = fields.Char(string="ID endereço")
    latitude = fields.Char(string="Latitude")
    longitude = fields.Char(string="Longitude")
    tipo_survey = fields.Char(string="Tipo Survey")
    rede_interna = fields.Char(string="Rede Interna")
    ums_certificadas = fields.Char(string="UMS Certificadas")
    rede_edif_cert = fields.Char(string="Rede edif cert")
    disp_comercial = fields.Char(string="Disponibilidade Comercial")
    estado_controle = fields.Char(string="Estado de controle")
    id_celula = fields.Char(string="ID da celula")
    quantidade_hcs = fields.Char(string="Quantidade HCS")